version: '2'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: divyanshchauhan1583
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
